[App]
Name = "ai.h2o.wave.studio"
Version = "{{VERSION}}"
Title = "Wave Studio"
Description = "In-browser IDE for building Wave apps."
Tags = ["APP_DEV"]
LongDescription = "about.md"

[Runtime]
Module = "studio"
RoutingMode = "BASE_URL"

[[Env]]
Name = "H2O_WAVE_PUBLIC_DIR"
Value = "/assets/@../../app/static/"